matrix mul part 2

diff --git a/Assgn1/run b/Assgn1/run
--- a/Assgn1/run
+++ b/Assgn1/run
@@ -50,6 +50,58 @@ run_mat_stats() {
     cat "${root}/accum" | python3 calc_speedup.py >> "${root}/speedups"
 }
 
+mat_mul_part_2_run() {
+    root=$1
+    sched_policy=$2
+    chunk_sz=$3
+    
+    export OMP_DISPLAY_ENV=true
+    export OMP_SCHEDULE="${sched_policy}, ${chunk_sz}"
+    export OMP_NUM_THREADS=12
+
+    echo $OMP_SCHEDULE
+
+    f="${root}/${sched_policy}-${chunk_sz}"
+    
+    mkdir -p "${f}"
+       
+    output=$(bin/mat_mul 1000 2>"${f}/omp_info")
+
+    echo $output >> "${f}/base"
+    echo $output " # ${sched_policy}-${chunk_sz}" >> "${root}/accum"
+
+    if [ $? -ne 0 ]; then
+        echo "encountered error"
+        exit 1
+    fi
+}
+
+mat_mul_part_2() {
+    root=out/mat_mul
+
+    if [ $clean -eq 1 ]; then
+        rm -rf $root
+    fi
+    
+    mkdir -p $root
+
+    export OMP_DISPLAY_ENV=true
+    
+    echo "[" >> "${root}/accum"
+
+    mat_mul_part_2_run $root 'STATIC' '10'
+    mat_mul_part_2_run $root 'STATIC' '100'
+    mat_mul_part_2_run $root 'STATIC' '1000'
+
+    mat_mul_part_2_run $root 'DYNAMIC' '10'
+    mat_mul_part_2_run $root 'DYNAMIC' '100'
+    mat_mul_part_2_run $root 'DYNAMIC' '1000'
+    
+    echo "]" >> "${root}/accum"
+    
+    #run_mat_stats $root    
+}
+
 mat_mul() {
     root=out/mat_mul
 
@@ -140,6 +192,7 @@ case "$command" in
     "")       affinity ;;
     affinity) affinity ;;
     mat_mul)  mat_mul ;;
+    mat_mul_2) mat_mul_part_2 ;;
     *) ;;
 esac
 
